# Generated by Django 2.2.13 on 2020-06-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stud_class',
            new_name='std_class',
        ),
    ]
