# Generated by Django 2.2.16 on 2020-10-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200628_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.TextField()),
                ('name', models.TextField(max_length=40)),
                ('std_class', models.TextField()),
                ('dept', models.TextField()),
                ('year', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.TextField(default='10/10/2020'),
            preserve_default=False,
        ),
    ]
