# Generated by Django 2.2.16 on 2020-10-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
    ]
