# Generated by Django 3.0.7 on 2020-10-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20201019_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.TextField(default='null'),
        ),
    ]
