# Generated by Django 3.0.7 on 2020-10-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_Subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='dept',
            field=models.TextField(default='CS'),
            preserve_default=False,
        ),
    ]
