# Generated by Django 2.2.16 on 2020-11-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='student',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Book', to='student.Student'),
        ),
    ]
