# Generated by Django 2.2.16 on 2020-11-22 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_book_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='student',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='Book', to='student.Student'),
        ),
    ]
