# Generated by Django 2.2.16 on 2020-11-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20201122_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='student',
            field=models.ManyToManyField(to='student.Student'),
        ),
    ]
